### ISSUE TITLE
Onlineanzeige bei l2tp

### ISSUE THREAD

**Issue by ChristianDresel** [asdil12/fff-monitoring#29]
Wenn ein Router nur noch per l2tp verbunden ist, wird der WAN Haken zu einen Kreuz. Z.b.

https://monitoring.freifunk-franken.de/routers/5629310644ce6e7393236f78

Für L3 Gateways gilt das gleiche:

https://monitoring.freifunk-franken.de/routers/579daef89369c31f138d6c61

Eventuell sollte man die Erkennung grundsätzlich ändern?

**Comment by asdil12** [comment]
Ja - es wäre besser, wenn der Router direkt ins XML schreibt, ob er WAN hat.

So wird es aktuell erkannt, ob ein Router WAN hat:
https://github.com/asdil12/fff-monitoring/blob/master/ffmap/routertools.py#L248

**Comment by ChristianDresel** [comment]
Denke auch das dies die beste Lösung wäre:

--> https://mantis.freifunk-franken.de/view.php?id=30

**Comment by adridolf** [comment]
Wieso steht da eigentlich in Zeile 20 (https://github.com/asdil12/fff-monitoring/blob/master/ffmap/routertools.py#L20) l2tp2? Wenn ich am Router (WR841N) iwconfig mache, habe ich da l2tp0 und l2tp1... Entsprechend würde ich erwarten, dass nach letzteren beiden überprüft wird... Oder stehen die da immer?

**Comment by adridolf** [comment]
mMn müsste es reichen, wenn man in Zeile 20 l2tp0 einträgt und die Erkennung läuft auf allen Routern auch ohne Firmware-Update. Oder man fügt halt noch nen Check nach Zeile 248 ein und überprüft l2tp0 und l2tp1 ...

**Comment by adridolf** [comment]
Könnte dann z.B. so aussehen (Dateinamen sind random):
[routerdiff.patch.txt](https://github.com/asdil12/fff-monitoring/files/1038102/routerdiff.patch.txt)
(Immer noch unter der Prämisse, dass ich das richtig verstehe ...)

**Comment by adridolf** [comment]
Hab das Ganze jetzt noch ein bisschen ausgebaut, sodass wie in meinem Commit zum Router-WebUI sowohl fastd als auch L2TP angezeigt werden. Bin aber zu dumm (oder darf das vll. gar nicht), einen Pull-Request daraus zu machen (ist jetzt aber zumindest ein richtiger Patch):

[0001-Show-WAN-uplink-status-for-both-fastd-and-l2tp-indiv.patch.txt](https://github.com/asdil12/fff-monitoring/files/1038380/0001-Show-WAN-uplink-status-for-both-fastd-and-l2tp-indiv.patch.txt)

**Comment by ChristianDresel** [comment]
hi

ich fände es schöner, wenn die Router sagen "heyho ich hab VPN mach mal nen Haken statt ein Kreuz":

https://mantis.freifunk-franken.de/view.php?id=30

mfg

Christian

**Comment by ChristianDresel** [comment]
https://mantis.freifunk-franken.de/view.php?id=30#c98

bitte prüfen ob sich das einfach einbauen lässt

**Comment by kratz00** [comment]
`<data>
    <system_data>
        <vpn_active>1 oder 0</vpn_active>
    </system_data>
</data>
`
Sowas laesst sich einfach umsetzen.
Wollen wir _vpn_active_ eventuell in _has_was_uplink_ umbenennen?
_vpn_active_ finde ich persoenlich nicht sehr aussagekraeftig.

**Comment by adridolf** [comment]
Im Moment prüfe ich im Code halt, ob fastd oder l2tp Adapter existieren. Da fand ich vpn_active präziser. Wenn jemand, der mehr vom Netz versteht als ich, sagt, das has_wan_uplink besser ist, kann ich das aber genauso reinschreiben lassen.

**Comment by ChristianDresel** [comment]
eigentlich war die Meinung auf der ML ja jetzt eher, es geht um VPN. Wenn wir gegen WAN Uplink prüfen ist wieder die Frage was ist mit so Gateways wie Hardhöhe und StPaul? Wie definiert man "WAN Uplink" eigentlich genau? VPN ist da deutlich einfacher zu definieren. Ich bin dafür es bei VPN zu belassen.

**Comment by asdil12** [comment]
Wie macht man VPN ohne dazu wan zu verwenden?

**Comment by adridolf** [comment]
Hab mal vpn_active und l2tp für ältere Firmwares in einen Patch gebaut. Entsprechend Christians Wunsch könnte man noch überlegen, ob man den Punkt WAN Uplink einfach in VPN aktiv umbenennt?

**Comment by adridolf** [comment]
Nachdem der Patch applied ist, bei WAN Uplink aber bei vielen meiner Router immer noch das Kreuz angezeigt wird, gehe ich davon aus, das der Patch nicht funktioniert hat?
z.B. https://monitoring.freifunk-franken.de/routers/572e1cc49369c3633aa4144d

**Comment by kratz00** [comment]
Firmware 20170110 schickt die Daten doch noch gar nicht in dem Format, wie dein Patch sie erwartet, oder hast du die Firmware nachtraeglich veraendert?

**Comment by asdil12** [comment]
Ich habe nichts an der Firmware geändert.

**Comment by adridolf** [comment]
Der hier schickt vpn_active und hat ein Kreuz: https://monitoring.freifunk-franken.de/routers/59022c439369c305f1b98c83

Und durch die Änderung beim Parsen von l2tp sollte der Haken doch auch bei alter Firmware funktionieren?

**Comment by kratz00** [comment]
Jetzt sollte es gehen, die Aenderungen war noch nicht "live".
Danke fuer deinen Patch @adridolf 

@asdil12 Ich denke du kannst das Ticket jetzt schliessen.

**Comment by asdil12** [comment]
Dann hab ich das Einspielen wohl vergessen...
