### ISSUE TITLE
Falls Router im Datensatz Hood mitschickt, diese verwenden

### ISSUE THREAD

**Issue by ChristianDresel** [asdil12/fff-monitoring#31]
Falls ein Router in seinen Alfreddatensatz mitschickt in welcher Hood er ist, sollte dies ausgewertet werden und der Router in diese Hood mit reingezählt werden. Gibt es diese Hood noch nicht, so sollte diese angelegt werden.

--> https://mantis.freifunk-franken.de/view.php?id=38

**Comment by asdil12** [comment]
Ich kann die Hood einfach für den Router anzeigen, aber neu anlegen ist nicht so einfach, da ich dafür die Koordinaten kennen müsste.

**Comment by ChristianDresel** [comment]
hi

Die Hoods um die es geht haben keine Koordinaten in diesem Sinne. Es handelt sich z.b. um Neunhof:
https://monitoring.freifunk-franken.de/map?mapcenter=49.52184,11.05877,16
All diese Router sind in ihrer eigenen Hood, um dort reinzukommen kann man sich nicht per VPN / Koordinaten verbinden (diese Hood hat keinen VPN Endpunkt/Server), sondern man muss mich per WLAN (oder Kabel oder oder...) erreichen und dann die Daten manuell einstellen. 
Es werden mittlerweile immer mehr aufbauten die nach dieser Art laufen, aktuell sind es 4 und mindestens ein weiterer ist noch geplant und wer weiß was die Zukunft bringt.

**Comment by asdil12** [comment]
Wenn die Router kein VPN haben - wie erreichen sie dann den Alfred Master?

**Comment by ChristianDresel** [comment]
hi
Auf einen der Router läuft Alfred als Master und dazu @kratz00 sein calfred
https://github.com/kratz00/firmware/tree/calfred
Ins Internet kommen sie per L3 Anbindung etwa so:
https://wiki.freifunk-franken.de/w/Babel_und_dnsmasq_in_unsere_firmware
Ist aktuell einfach der neueste Schrei und so bleiben die L2 Broadcastdomänen klein und das ganze wird richtig schnell mit sehr wenig Overhead :)

**Comment by asdil12** [comment]
Kannst du mir ein Beispiel XML schicken?

**Comment by ChristianDresel** [comment]
Hallo

folgender Router müsste eine erweitere XML mitschicken (scheint dem Monitoring nicht zu stören und es frisst die Daten anscheinend weiterhin problemlos):

https://monitoring.freifunk-franken.de/routers/579daef89369c31f138d6c61

aussehen sollte die XML so (Absätze sind zum besseren kenntlich machen und werden NICHT mit gesendet:

http://fff-gw-cd1.fff.community/zerobin/?e504599379b33587#h9uH3z25sF1t32ODMXl7cEBooUezQpuSmsRpgJkJyso=

Prinzipiell gilt:

Ist das Feld <hood> belegt, sollte diese Hood eingetragen werden, gibt es die noch nicht soll sie angelegt werden (auch unter Statistik & co sollte sie mit aufgeführt werden).
Ist das Feld leer also <hood></hood> oder gar nicht vorhanden dann soll die Hood wie bisher auch aus den Koordinaten ermittelt werden.

Falls noch Rückfragen sind, sag einfach bescheid.

mfg

Christian

**Comment by asdil12** [comment]
Ich konvertiere den hoodnamen in Kleinbuchstaben beim Import.

**Comment by asdil12** [comment]
Die Hood wird nicht extra in der hood "tabelle" angelegt, da die statistik einfach eine gruppierung über die routertabelle vornimmt.
