### ISSUE TITLE
Hoodname anklickbar machen

### ISSUE THREAD

**Issue by ChristianDresel** [asdil12/fff-monitoring#32]
Hi

Danke erstmal für die Arbeit mit der Hood, schaut gleich viel schöner aus :+1: )

Eine Sache hätte ich jetzt noch:
Überall wo ein Hoodname steht, sollte dieser anklickbar sein.
Am schönsten wäre es, wenn dann auf die Map Seite weitergeleitet wird dort aber nur die Router der angeklickten Hood angezeigt werden, vllt. über einen Parameter in der URL oder so?

Gruß Christian

**Comment by asdil12** [comment]
> Überall wo ein Hoodname steht, sollte dieser anklickbar sein.
Das würde nur bei den Hoods mit Koordinaten funktionieren.

> Am schönsten wäre es, wenn dann auf die Map Seite weitergeleitet wird dort aber nur die Router der angeklickten Hood angezeigt werden, vllt. über einen Parameter in der URL oder so?
Das geht nicht, weil die Karte mit allen Routern auf dem Server generiert wird.

**Comment by ChristianDresel** [comment]
Hi

stimmt du hast recht :( Mein "Problem" aktuell ist, ich seh auf der Statistikseiten die Hoods Unterfuerberg, Fablabnbg und Neunhof... Nur wie findet man nun "schnell" heraus welche Router da eigentlich dahinter stecken? Vielleicht fällt dir ja eine schöne Lösung dazu ein?

Gruß Christian

**Comment by asdil12** [comment]
> stimmt du hast recht :( Mein "Problem" aktuell ist, ich seh auf der Statistikseiten die Hoods Unterfuerberg, Fablabnbg und Neunhof... Nur wie findet man nun "schnell" heraus welche Router da eigentlich dahinter stecken? Vielleicht fällt dir ja eine schöne Lösung dazu ein?
https://monitoring.freifunk-franken.de/routers?q=hood%3Aneunhof

**Comment by ChristianDresel** [comment]
Das sieht gut aus, vllt. kann man von der Statistikseite dann darauf verlinken?
