### ISSUE TITLE
Netmon Abhängigkeiten entfernen

### ISSUE THREAD

**Issue by ChristianDresel** [asdil12/fff-monitoring#33]
Hi

da der Netmon nun nicht mehr existiert kann alles entfernt werden was in irgendwelcherweise vom Netmon abhängt (und auch alle Issues zum Thema Netmon hier können zugemacht werden da sie damit hinfällig sind). Auf Anhieb fällt mir das ganze sync Zeug ein sowie der Button Actions -> Trigger Netmon Sync. Auch der legacy Provider ist aus und auch da kann alles entfernt werden.

Gruß Christian

**Comment by loki-kun** [comment]
Hallo,
ich habe malt mit den Button angefangen und Arbeite mich langsam durch

**Comment by asdil12** [comment]
Sollte in PR #35 sein.
