### ISSUE TITLE
Blaue Linien für L3 Verbindungen

### ISSUE THREAD

**Issue by ChristianDresel** [asdil12/fff-monitoring#38]
Hallo

da nun immer mehr Router per Layer 3 Richtfunk miteinander verbunden sind, bräuchten wir dafür auch schöne Linien und eine Nachbarn Anzeige.
Ich hab mal grundsätzlich angefangen eine XML mitzuschicken, das sollte aktuell dieser Router tun:

https://monitoring.freifunk-franken.de/routers/579daef89369c31f138d6c61

Er schickt in der XML folgendes mit:

<babel_neighbour><neighbour_0><originator>fe80::6666:b3ff:fede:f5cd</originator><nexthop>fe80::6666:b3ff:fede:f5cd</nexthop><outgoing_interface>eth0.4</outgoing_interface></neighbour_0><neighbour_1><originator>fe80::c11:12:15:da5</originator><nexthop>fe80::c11:12:15:da5</nexthop><outgoing_interface>fffgwcd1VPN</outgoing_interface></neighbour_1></babel_neighbour>

Es sollten nun blaue Linien zu den Routern gezogen werden, die diese fe80 Adresse haben (leider gibt mir Babel keine anderen Daten raus, daher wäre fe80:: für mich das einfachste, ich hoffe das ist kein großes Problem im Monitoring?).
Dabei gibt es zu beachten, das nicht jeder Nachbar auch auf der Karte ist. So ist z.b. in diesem Fall neighbour_1 ein Server im RZ welcher nur per VPN angebunden ist. Da den seine fe80:: nicht im Montioring auftauchen wird, kann dieser auch ignoriert werden. Die andere fe80:: <neighbour_0> in diesen Fall trifft z.b. auf diesen Router zu:

https://monitoring.freifunk-franken.de/routers/58e8a2c69369c3065adb1efb

Es sollte also dieser Router als Nachbar hinzugefügt werden und dorthin eine blaue Linie auf der Map dazu kommen.

Aktuell ist noch keine Metrik/Quality Berechnung mit dabei, kann sein das dies im 2. Schritt noch folgen wird. Ich möchte aber erstmal so schnell wie möglich so einfach wie möglich die Linie haben ;) 

Vielen Dank

mfg

Christian

**Comment by kratz00** [comment]
I started working on this.
