### ISSUE TITLE
Statusleiste Link zum Freifunk Franken Wiki

### ISSUE THREAD

**Issue by ChristianDresel** [asdil12/fff-monitoring#44]
Ich wurde jetzt schon mehrfach angesprochen das man zwar von https://wiki.freifunk-franken.de/w/Hauptseite direkt zum Monitoring kommt, vom Monitoring aber nicht mehr zurück. Irgendwo oben in der Leiste ein Link zurück zum Wiki wäre nett.

**Comment by asdil12** [comment]
Dazu muss einfach nur ein `<li><a></a></li>` in der Zeile nach dem `endfor` eingefügt werden:

https://github.com/asdil12/fff-monitoring/blob/master/ffmap/web/templates/bootstrap.html#L43
