### ISSUE TITLE
MAC - Nodename alias Liste für Wifi Analyzer

### ISSUE THREAD

**Issue by manuelreiter** [asdil12/fff-monitoring#47]
Bei WifiAnalyzer kann man eine Aliasliste erstellen. 
https://play.google.com/store/apps/details?id=com.farproc.wifi.analyzer&hl=de
So sieht man anstatt der SSID den Nodenamen.
Die formatierung: 

#----------WifiAnalyzer alias file----------
#
#Encoding: UTF-8.
#The line starts with # is comment.
#
#Content line format:
#bssid1|alias of bssid1
#bssid2|alias of bssid2

https://pastebin.com/yvT878ES  (Habe noch FFF- vorangestellt)
Gibt es eine möglichkeit die MAC Adressen mit zugehörigem Nodename zu exportieren (pro hood)?

**Comment by manuelreiter** [comment]
Die Liste könnte man dann auch gebrauchen um beim WifiScan auf dem Freifunkrouter die Nodenamen anzeigen zu lassen anstatt die SSID (https://mantis.freifunk-franken.de/view.php?id=50)

**Comment by meskal** [comment]
Falls jemand den Export einer solchen Liste implementiert, könnte er vielleicht auch dran denken sie zusätzlich auch als bat-hosts file zu generieren. Das könnte dann bei der Nutzung von batctl nützlich sein.

https://downloads.open-mesh.org/batman/manpages/batctl.8.html (Abschnitt *FILES*)

**Comment by manuelreiter** [comment]
ist das dann damit möglich?

grettz,
manu.


        *translate*|*t*  *MAC_address*|*bat-host_name*|*host_name*|*IP_address*

               Translates a destination (hostname, IP, MAC, bat_host-name) to
               the originator mac address responsible for it.



root@Gasthof-Rittmayer-Keller:~# batctl translate AischerKerwa2017
Error - mac address of the ping destination could not be resolved and is 
not a bat-host name: AischerKerwa2017
root@Gasthof-Rittmayer-Keller:~# batctl translate 86:16:F9:66:41:58
86:16:f9:66:41:58
root@Gasthof-Rittmayer-Keller:~#


Am 02.08.2017 um 17:34 schrieb meskal:

**Comment by asdil12** [comment]
Von welchem interfaces muss das die mac sein?
br-mesh?

**Comment by meskal** [comment]
Ich hab das selber noch nie ausprobiert. Aber vermutlich br-mesh. Das sollten ja auch die MACs sein die bei *batctl o* auftauchen.

**Comment by adridolf** [comment]
Der Patch für den WifiAnalyzer ist ja (so gut wie) durch.
Das mit dem bat-hosts versteh ich nicht genau. Mag jemand eine Beispiel-Output-Datei bauen und verlinken, dann schreib ich dafür auch ei api-Skript...

**Comment by adridolf** [comment]
Close this, batctl subtopic moved to https://github.com/asdil12/fff-monitoring/issues/78.

**Comment by adridolf** [comment]
Bitte den hier schließen, da verschoben.
