### ISSUE TITLE
Avg Load Graph

### ISSUE THREAD

**Issue by ChristianDresel** [asdil12/fff-monitoring#55]
Hallo

ich fände einen avg load Graph nicht schlecht. Ich hab aktuell einen Router mit hoher Auslastung und hohen Load Werten, da würde mir ein Graph bei der Diagnose sehr helfen.
Die Daten werden in der Json ja schon mitgeschickt, es müsste "nur" ein Graph gebaut werden.

Gruß Christian

**Comment by manuelreiter** [comment]
Hi,
so ein Graph pro hood wäre echt nice...
greetz,
manu.

**Comment by adridolf** [comment]
Hallo Christian,

erklär mir bitte mal genauer, um welche Daten es geht ...

Grüße

Adrian

**Comment by ChristianDresel** [comment]
hi

https://monitoring.freifunk-franken.de/routers/59650cce9369c306770af5df?json

Es gibt dort einen Wert:

...
"loadavg": 0.51,
...

dafür hätte ich im Monitoring gerne einen Graphen wie wir schon für Memory & Processes haben

mfg

Christian

**Comment by asdil12** [comment]
@adridolf du hast noch eine sache vergessen in deinem PR - siehe https://github.com/asdil12/fff-monitoring/commit/058bed9a2effcd4526edc1270935fa498269e4e7

Das ist jetzt alles live und sollte jetzt funktionieren.

**Comment by adridolf** [comment]
Das erklärt einiges. Danke fürs fixen.

**Comment by asdil12** [comment]
Mein Patch sorgt erst dafür, dass der loadavg wert im Verlauf (und nicht nur immer der neuste) gespeichert wird.
