### ISSUE TITLE
Kein WebUI link wenn andere ULA Adresse

### ISSUE THREAD

**Issue by loki-kun** [asdil12/fff-monitoring#66]
Wenn der Router eine andere ULA Adresse als fdff:: hat wird auf https://monitoring.freifunk-franken.de/routers/ kein WEBUI Link erzeugt

**Comment by asdil12** [comment]
Das ist so programmiert - ja. Wie soll ich die richtige ip denn sonst erkennen?

Der aktuelle Algorithmus nimmt die IP, die mit `fdff` anfängt und 16-20 Zeichen lang ist.

https://github.com/asdil12/fff-monitoring/blob/f51d0ae5fdc81bc1885b11abc5175a91a24f7160/ffmap/web/filters.py#L183

**Comment by loki-kun** [comment]
ok, habe mir den code jetzt nicht ganz durchgelesen. Sollten wir also Irgendwann mal den ULA Prefix oder den Interface Namen ändern müsste das dann halt angepasst werden.
