### ISSUE TITLE
Router Seite, Average Statistik wird nicht angezeigt, bei Interfaces nichts auswählbar

### ISSUE THREAD

**Issue by loki-kun** [asdil12/fff-monitoring#69]
Fehler passiert in Version 61.0.3163.91 (Offizieller Build) (64-Bit)
Firefox 55.0.3 (64-Bit) nicht betroffen.

59c0f9e79369c36749e72188:398 Uncaught ReferenceError: loadavg_graph is not defined
    at HTMLDocument.<anonymous> (59c0f9e79369c36749e72188:398)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)
(anonymous) @ 59c0f9e79369c36749e72188:398
j @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
J @ jquery.min.js:2

**Comment by adridolf** [comment]
F5 bzw. Strg+F5 nützen auch nix?

**Comment by loki-kun** [comment]
Ich hatte beides vor dem Update schon probiert, komischerweise tuts jetzt.
