### ISSUE TITLE
ES2015 support for old browsers

### ISSUE THREAD

**Issue by mojoaxel** [asdil12/fff-monitoring#7]
A lot of browsers do not jetzt support all ES2015 features yet (e.g. for...of).
You should use something like [bable.js](https://babeljs.io/) to also older or more alternativ browsers.

**Comment by asdil12** [comment]
Which part of the js code are you refering to?

**Comment by mojoaxel** [comment]
There are multible for-of loops (e.g. in [map.js:73](https://github.com/asdil12/ff-map/blob/master/ffmap/web/static/js/map.js#L73)).

Also you use some modern CSS3 features, what is cool, but also not well supported. (e.g. the css calc function  [map.html:14](https://github.com/asdil12/ff-map/blob/master/ffmap/web/templates/map.html#L14))

**Comment by mojoaxel** [comment]
This an issue e.g. in Chromium 22 on Debian 7
