### ISSUE TITLE
Leerzeichen in Hoodname macht Probleme

### ISSUE THREAD

**Issue by ChristianDresel** [asdil12/fff-monitoring#70]
Hallo

Wenn in der Hood ein Leerzeichen ist, geht der Hoodfilter nicht:

https://monitoring.freifunk-franken.de/routers?q=hood%3Afuerth+v2
https://monitoring.freifunk-franken.de/routers/599698b79369c3066b360efe (wenn man den Hoodnamen anklickt, findet er dazu keine Router was ja eindeutig falsch ist)

mfg

Christian

**Comment by asdil12** [comment]
Die einfachste Lösung wäre es, wenn Hoodnamen statt leerzeichen einen Unterstrich bekommen würden.

Wenn ich jetzt im Monitoring einen Hack einbaue, der Leerzeichen als Unterstriche darstellt (Leerzeichen selbst dienen in der Suchmaske der Separierung von Suchparametern), dann kann man keine Hoodnamen mit echten Unterstrichen mehr darstellen.

**Comment by adridolf** [comment]
Ich bin ja generell der Meinung, dass man einfach keine Leerzeichen in Hoodnamen reintun sollte.

Wenn es allerdings weiter in Richtung Dezentralität geht, können wir das aber ja ohnehin nicht vorschreiben und das Problem wird uns wahrscheinlich immer mal wieder begegnen.

**Comment by adridolf** [comment]
Ich bin immer noch der Meinung, dass man keine Leerzeichen in Hoodnamen reintun sollte.

Im neuen Monitoring hab ich das Leerzeichen-Problem jetzt behoben.

Bitte schließen.
