### ISSUE TITLE
keyxchangev2 braucht weiteren Layer

### ISSUE THREAD

**Issue by ChristianDresel** [asdil12/fff-monitoring#71]
hi

da der keyxchangev2 nun in die entscheidene Phase gelangt brauchen wir dazu einen neuen Layer auf der Map. Rechts oben bei den 3 Blättern sollte unter den Haken "Hoods" noch ein Haken "HoodsV2" dazu kommen und dann mit den folgenden Daten die Linien gezeichnet werden:

http://keyserver.freifunk-franken.de/v2/hoods.php

mfg

Christian

**Comment by asdil12** [comment]
Soll ich wirklich einfach nur ein overlay einrichten?
Die Router bekommen ihre hood aktuell anhand der Monitoring Datenbank.
Es wäre einfacher, wenn es eine mehr oder weniger harte Umstellung auf das neue System geben würde.
Dann würde ich das Monitoring so einstellen, dass es sich einfach regelmäßig die Hoods vom Keyserver holt.

Die Frage ist also: Ab wann soll ich die Hood über den KeyexchangeV2 für die Router ermitteln?
Oder schicken alle KEYEXv2-Router die Hood sowiso über das Nodewatcher XML mit?

Offtopic: Was ist denn am KeyExchangeV2 anders?

**Comment by adridolf** [comment]
> Oder schicken alle KEYEXv2-Router die Hood sowiso über das Nodewatcher XML mit?
Ja. Die Router müssen nicht mehr über das Monitoring einer Hood zugewiesen werden.

Entsprechend kann alt und neu im Monitoring friedlich nebeneinander existieren.

**Comment by ChristianDresel** [comment]
Die Router schicken im KeyXchangeV2 nun ihre Hood selbst mit, da sie diese nun kennen. Am KeyXchangeV2 wurde erweitert, das der Router nun mehr Infos bekommt:
http://keyserver.freifunk-franken.de/v2/?lat=49.48&long=10.9
Und noch viele Kleinigkeiten die dezentrale Hoods einfacher betretbar machen :)

Also ja, wie @adridolf sagt, einfach nur ein Overlay reicht tatsächlich komplett aus ;) Die Router sind ja schon in der richtigen Hood siehe hier:
https://monitoring.freifunk-franken.de/routers?q=hood%3Afuerthv2
https://monitoring.freifunk-franken.de/routers?q=hood%3Anurembergv2
https://monitoring.freifunk-franken.de/routers?q=hood%3Ahassfurtv2

mfg

Christian

**Comment by adridolf** [comment]
Resolved.

**Comment by adridolf** [comment]
Man kann im neuen Monitoring sowohl Hoodsv2 als auch Routerv2 ein- und ausschalten.

Bitte schließen!
