### ISSUE TITLE
WebUI-Link über ULA

### ISSUE THREAD

**Issue by adridolf** [asdil12/fff-monitoring#72]
Da wir beim neuen KeyExchangeV2 ULA-Adressen vergeben können, sollten entsprechende Router über diese zum WebUI verlinkt werden. Siehe auch:
https://github.com/asdil12/fff-monitoring/issues/66

Werde das evtl. selbst implementieren, dies dient nur als Erinnerung.

**Comment by asdil12** [comment]
Ist nur die Frage, ob man das dann überhaupt noch in der mongodb speichert, oder lieber direkt vom key Exchange die Daten holt.

**Comment by adridolf** [comment]
Ich würde einfach die Adresse nehmen, die der Router mitschickt. Wenn er eine fd8-Adresse hat, wird die genommen, wenn nicht wird die fdff genommen, Das funktioniert für neu und alt und man muss keine neuen Schnittstellen bauen.
