### ISSUE TITLE
Orphaned Router-Delay wieder vergrößern

### ISSUE THREAD

**Issue by adridolf** [asdil12/fff-monitoring#77]
Ich bin dafür, das Delay wieder auf 60 oder 90 Tage zu setzen, denn:
- Der Einfluss auf die Performance sollte im Gegensatz zur allg. Statistik (für JEDEN Router) gering sein
- Die Performance sollte generell wieder besser sein, da ich wohl maßgeblich die Performance-Probleme verursacht habe
- Es ist unheimlich hilfreich, wenn du so einen alten router wiederbelebst und dann stehen die daten noch irgendwo. Hab kürzlich einen Ersatzrouter vorbereitet und musste dann die Koordinaten raten, weil ich nicht nachschauen konnte, wo der alte steht. Genau dafür sind in meinen Augen die Daten eines offline Routers aber da. (Zum Gluck haben wir eine Datei wo Namen und Macs drin stehen)
- Auch die diagnose eines kaputten routers macht ja nicht jeder innerhalb von 8 Tagen

Beste Grüße

Adrian

**Comment by asdil12** [comment]
done
