### ISSUE TITLE
Koordinaten als Text in Routerdetailpage anzeigen

### ISSUE THREAD

**Issue by adridolf** [asdil12/fff-monitoring#80]
Hatte schon oft das Problem, dass ich einen gebrickten Router ersetzen wollte. Hier kriegt man alles aus dem Monitoring, außer die Koordinaten (zumindest ohne im Code zu wühlen).

Implementierung mach ich demnächst voraussichtlich selbst.

Hat jemand ein Problem, wenn das einfach mit bei den Routerdetails steht?

**Comment by asdil12** [comment]
Es gibt den Trick, ?json an die Router URL zu hängen

Am 20. Oktober 2017 16:47:04 MESZ schrieb Adrian Schmutzler <notifications@github.com>:
>Hatte schon oft das Problem, dass ich einen gebrickten Router ersetzen
>wollte. Hier kriegt man alles aus dem Monitoring, außer die Koordinaten
>(zumindest ohne im Code zu wühlen).
>
>Implementierung mach ich demnächst voraussichtlich selbst.
>
>Hat jemand ein Problem, wenn das einfach mit bei den Routerdetails
>steht?

**Comment by adridolf** [comment]
Werde das nicht weiter verfolgen.
